name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          #flutter-version-file: pubspec.yaml # path to pubspec.yaml
        
      #- run: flutter pub get
      - run: flutter build web --release

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # upload entire directory
          path: './build/web/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
